'''Create a class named Order that stores
The name of the burger
How many times it has been ordered
The price of the burger
Create a method named GenerateOrders
This method will return a List of Order
Generate 100 orders
Add the orders to the List
Create a method named FindPopular that takes a List as a parameter
The method should return with the following tuple:
The name of the most ordered burger
How many times it has been ordered
The amount of income
Test your solution in the Main method'''
import random
class Order:
    def __init__(self, name, price):
        self.name = name
        self.count = 0
        self.price = price
        
    def increment_count(self):
        self.count += 1

def GenerateOrders():
    orders = []
    for i in range(100):
        # Generate random burger name and price
        burger_name = "Burger " + str(i)
        burger_price = round(random.uniform(3, 10), 2)
        order = Order(burger_name, burger_price)
        order.increment_count()
        orders.append(order)
    return orders

def FindPopular(orders):
    popular_burger = None
    popular_count = 0
    income = 0
    for order in orders:
        if order.count > popular_count:
            popular_burger = order.name
            popular_count = order.count
            income = order.count * order.price
    return (popular_burger, popular_count, income)

if __name__ == "__main__":
    orders = GenerateOrders()
    popular_burger, count, income = FindPopular(orders)
    print("The most popular burger is:", popular_burger)
    print("It has been ordered:", count, "times")
    print("The income generated by this burger is:", income)
